set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.config/nvim/bundle/Vundle.vim
call vundle#begin('~/.config/nvim/bundle')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdcommenter'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
filetype plugin on

" Theme
" set t_Co=256
" let base16colorspace=256
" set background=dark
" colorscheme base16-codeschool

let mapleader=","

syntax enable

set autoindent
set backspace=indent,eol,start
set cursorline
"set encoding=utf-8
set gdefault
set hidden
set history=50
set iskeyword-=
set mouse=a
set number
set ruler
set scrolloff=3
set showcmd
set showmode
set ttyfast
set visualbell
set wildmenu
set wildmode=list:longest
set viminfo="NONE"
set laststatus=2             " Status bar
set noswapfile               " Disale swap files
set splitbelow               " Horizontal split below current
set splitright               " Vertical split to right of current

" Wrap column settings
" set colorcolumn=75
" set formatoptions=qrn1
" set textwidth=79
" set wrap

" Tabbing settings
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

" Search/Highlight tweaks
set hlsearch
set ignorecase
set incsearch
set showmatch
set smartcase

" Disable moving with arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
